version: 2
updates:
  - package-ecosystem: 'github-actions'
    commit-message:
      prefix: 'ğŸˆ '
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '06:00'
      timezone: 'Australia/Perth'
    groups:
      minor-patch:
        update-types:
          - 'minor'
          - 'patch'
  - package-ecosystem: 'gomod'
    commit-message:
      prefix: 'ğŸ¹ '
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '06:00'
      timezone: 'Australia/Perth'
    groups:
      minor-patch:
        update-types:
          - 'minor'
          - 'patch'
